# Generated by Django 3.0.7 on 2020-08-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_target', to='api.Payment'),
        ),
    ]
