# Generated by Django 3.0.7 on 2020-08-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200805_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_to',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_from',
        ),
    ]
