# Generated by Django 3.0.7 on 2020-09-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200827_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='initial_amount',
        ),
        migrations.DeleteModel(
            name='PaymentInitial',
        ),
    ]
