# Generated by Django 3.0.10 on 2020-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200907_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/bank/')),
            ],
        ),
    ]
