# Generated by Django 3.0.11 on 2020-11-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bankfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankfiles',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-10 10:10:10'),
            preserve_default=False,
        ),
    ]
