# Generated by Django 3.0.7 on 2020-08-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent_tag',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='tag',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
