# Generated by Django 3.0.7 on 2020-08-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200811_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tag'),
        ),
    ]
