# Generated by Django 3.0.7 on 2020-08-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transaction_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinitial',
            old_name='initial_amount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='paymentinitial',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_initial', to='api.Payment'),
        ),
    ]
