# Generated by Django 3.0.7 on 2020-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200813_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
